<?xml version="1.0"?>

<robot name="scanner" xmlns:xacro="http://www.w3.org/1999/XSL/Transform">
    <xacro:property name="base_size_x" value="0.298" />
    <xacro:property name="base_size_y" value="0.148" />
    <xacro:property name="base_size_z" value="0.07" />
    <xacro:property name="stand_size_x" value="0.075" />
    <xacro:property name="stand_size_y" value="0.012" />
    <xacro:property name="stand_size_z" value="0.3" />
    <xacro:property name="stand_offset_x" value="-0.003" />
    <xacro:property name="stand_offset_y" value="-0.018" />
    <xacro:property name="lidar_length" value="0.071" />
    <xacro:property name="lidar_radius" value="0.034" />
    <xacro:property name="lidar_offset_z" value="0.26" />
    <xacro:property name="laser_offset_y" value="0.063" />
    <xacro:property name="plate_length" value="0.012" />
    <xacro:property name="plate_diameter" value="0.146" />
    <xacro:property name="plate_offset_x" value="0.038" />
    <xacro:property name="plate_offset_y" value="0.077" />
    <xacro:property name="plate_offset_z" value="0.013" />

    <!-- main link -->
    <link name="world"/>
    <joint name="fixed" type="fixed">
        <parent link="world"/>
        <child link="base_link"/>
    </joint>

    <!--base-->
    <link name="base_link">
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${base_size_x} ${base_size_y}  ${base_size_z} "/>
            </geometry>
        </collision>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${base_size_x} ${base_size_y}  ${base_size_z} "/>
            </geometry>
            <material name="black">
                <color rgba="0.1 0.1 0.1 1"/>
            </material>
        </visual>
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="20"/>
            <inertia
                    ixx="0.1" ixy="0.1" ixz="0.1"
                    iyy="0.1" iyz="0.1"
                    izz="0.1"/>
        </inertial>
    </link>

    <!--lidar stand-->
    <link name="lidar_stand">
        <collision>
            <geometry>
                <box size="${stand_size_x} ${stand_size_y} ${stand_size_z}"/>
            </geometry>
            <material name="orange">
                <color rgba="1 0.45 0 1"/>
            </material>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <visual>
            <geometry>
                <box size="${stand_size_x} ${stand_size_y} ${stand_size_z}"/>
            </geometry>
            <material name="orange">
                <color rgba="1 0.45 0 1"/>
            </material>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </visual>
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="2"/>
            <inertia
                    ixx="0.1" ixy="0.1" ixz="0.1"
                    iyy="0.1" iyz="0.1"
                    izz="0.1"/>
        </inertial>
    </link>

    <joint name="base_to_lidar_stand" type="fixed">
        <origin xyz="-${base_size_x/2 - stand_size_x/2 + stand_offset_x} -${base_size_y/2 + stand_offset_y} ${base_size_z/2 + stand_size_z/2}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="lidar_stand"/>
    </joint>

    <!--lidar-->
    <link name="lidar">
        <collision>
            <geometry>
                <cylinder length="${lidar_length}" radius="${lidar_radius}"/>
            </geometry>
            <material name="orange"/>
            <origin rpy="-${pi/2} 0 0" xyz="0 0 0"/>
        </collision>
        <visual>
            <geometry>
                <cylinder length="${lidar_length}" radius="${lidar_radius}"/>
            </geometry>
            <material name="orange"/>
            <origin rpy="-${pi/2} 0 0" xyz="0 0 0"/>
        </visual>
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="1.2"/>
            <inertia
                    ixx="0.1" ixy="0.1" ixz="0.1"
                    iyy="0.1" iyz="0.1"
                    izz="0.1"/>
        </inertial>
    </link>

    <joint name="lidar_stand_to_lidar" type="fixed">
        <origin xyz="0 ${stand_size_y/2 + lidar_length/2} ${lidar_offset_z - stand_size_z/2}" rpy="0 0 0"/>
        <parent link="lidar_stand"/>
        <child link="lidar"/>
    </joint>

    <!--laser-->
    <link name="laser">

    </link>

    <joint name="lidar_to_laser" type="fixed">
        <origin xyz="0 ${laser_offset_y - lidar_length/2} 0" rpy="-${pi/2} ${pi/2} 0"/>
        <parent link="lidar"/>
        <child link="laser"/>
    </joint>

    <!--plate-->
    <link name="plate">
        <collision>
            <geometry>
                <cylinder length="${plate_length}" radius="${plate_diameter/2}"/>
            </geometry>
            <material name="orange"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <visual>
            <geometry>
                <cylinder length="${plate_length}" radius="${plate_diameter/2}"/>
            </geometry>
            <material name="orange"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </visual>
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="1"/>
            <inertia
                    ixx="0.1" ixy="0.1" ixz="0.1"
                    iyy="0.1" iyz="0.1"
                    izz="0.1"/>
        </inertial>
    </link>

    <joint name="base_link_to_plate" type="revolute">
        <origin xyz="${base_size_x/2 - plate_offset_x} ${base_size_y/2 - plate_offset_y} ${base_size_z/2 + plate_length/2 + plate_offset_z}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="1000" lower="0" upper="${pi*2}" velocity="3.054"/>
        <parent link="base_link"/>
        <child link="plate"/>
        <dynamics damping="50"/>
    </joint>

    <!--<joint name="base_link_to_plate" type="fixed">
        <origin xyz="${base_size_x/2 - plate_offset_x} ${base_size_y/2 - plate_offset_y} ${base_size_z/2 + plate_length/2 + plate_offset_z}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="plate"/>
    </joint>-->

    <transmission name="base_link_to_plate_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="base_link_to_plate">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_actuator">
            <mechanicalReduction>50</mechanicalReduction>
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </actuator>
    </transmission>

    <!--scan_object-->
    <link name="scan_object">

    </link>

    <joint name="plate_to_scan_object" type="fixed">
        <origin xyz="0 0 ${plate_length/2}" rpy="0 0 0"/>
        <parent link="plate"/>
        <child link="scan_object"/>
    </joint>

</robot>




