scanner_joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 500

base_to_arm1_controller:
 # type: "position_controllers/JointPositionController"
  type: "effort_controllers/JointPositionController"
  joint: base_link_to_plate
  pid: {p: 500000.0, i: 0.1, d: 20000.0}